name: Build and Publish
on: push
jobs:
  build:
    strategy:
      matrix:
        os:
          - value: windows-latest
            alias: windows
          - value: macOS-latest
            alias: mac
          - value: ubuntu-latest
            alias: ubuntu
    runs-on: ${{ matrix.os.value }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        flake8 photoorganizer.py --count --select=E9,F63,F7,F82 --show-source --statistics
    - name: Create Application
      run: |
        pyinstaller --onefile --name photo-organizer-${{ matrix.os.alias }} photoorganizer.py
    - name: Publish Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v1.0.${{ github.run_number }}
        files: dist/photo-organizer-*
        body: Commit ${{ github.sha }} from branch ${{ github.ref }}.
        draft: true
